version: '3.7'

services:
  invest_crm_api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ./src:/app
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.0-alpine
    volumes:
      - invest_crm_postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=invest_crm
      - POSTGRES_PASSWORD=fdc804cd
      - POSTGRES_DB=invest_crm
    ports:
      - 5433:5432

volumes:
  invest_crm_postgres_data: